INSERT INTO `artists` (`artist`) VALUES
('12th Planet'),
('A-Trak'),
('Aarab Muzik'),
('Adventure Club'),
('Afrojack'),
('Alesso'),
('Alex Metric'),
('Armin Van Buuren'),
('Art Department'),
('Arty'),
('ATB'),
('Avicii'),
('Axwell'),
('Bassnectar'),
('Benny Benassi'),
('Big Gigantic'),
('Bingo Players'),
('Borgore'),
('Botnek'),
('Bro Safari'),
('Calvin Harris'),
('Carl Cox'),
('Carnage'),
('Cazzette'),
('Cedric Gervais'),
('Clockwork'),
('Cosmic Gate'),
('Dada Life'),
('Dash Berlin'),
('David Guetta'),
('Deadmau5'),
('Dillon Francis'),
('Dimitri Vegas'),
('Like Mike'),
('Diplo'),
('Dirty South'),
('Disclosure'),
('Dj Snake'),
('Dog Blood'),
('DVBBS'),
('Dyro'),
('Eric Prydz'),
('Fat Boy Slim'),
('Fedde Le Grand'),
('Feed Me'),
('Ferry Corsten'),
('Flosstradamus'),
('Flux Pavilion'),
('Gareth Emery'),
('Hardwell'),
('Headhunterz'),
('John Dahlback'),
('Kaskade'),
('Knife Party'),
('Krewella'),
('Laidback Luke'),
('Loco Dice'),
('Luciano'),
('Luminox'),
('Madeon'),
('Major Lazer'),
('Mark Knight'),
('Markus Schulz'),
('Martin Solveig'),
('Mat Zo'),
('Morgan Page'),
('Nero'),
('Nervo'),
('Nicky Romero'),
('Paul Van Dyk'),
('Pete Tong'),
('Porter Robinson'),
('Pretty Lights'),
('Quintino'),
('R.L Grime'),
('R3hab'),
('Rebecca'),
('Fiona'),
('Richie Hawtin'),
('Rusko'),
('Sander Van Doorn'),
('Sebastian Ingrosso'),
('Seven Lions'),
('Showtek'),
('Sidney Samson'),
('Simon Patterson'),
('Solar Stone'),
('Steve Angello'),
('Steve Aoki'),
('Swedish House Mafia'),
('Thomas Gold'),
('Tiesto'),
('Tommy Trash'),
('Tritonal'),
('Umek'),
('UZ'),
('W&W'),
('Wildstylz'),
('Wolfgang Gartner'),
('Zedd'),
('Zeds Dead'),
('3LAU'),
('Above'),
('Beyond'),
('Aly'),
('Fila'),
('Atoms for Peace'),
('Brillz'),
('Candyland'),
('Carl Craig'),
('Chuckie'),
('Coone'),
('Crookers'),
('Dannic'),
('David Steven'),
('Deniz Koyu'),
('DJ Stephanie'),
('Dubfire'),
('Duck Sauce'),
('Dusky'),
('EDX'),
('Empire of The Sun'),
('Felix Da Housecat'),
('Flume'),
('Gina Star'),
('Isaac'),
('James Zabiela'),
('John Digweed'),
('Joker'),
('Joris Voorn'),
('Landis'),
('Crespo'),
('Martin Garrix'),
('Metrik'),
('Michael Woods'),
('Mixcloud Test'),
('MK (Marc Kinchen)'),
('Myon'),
('Shane 54'),
('Nadastrom'),
('New World Punx'),
('Nicolas Jaar'),
('Noir'),
('Owen Royal'),
('Partyraiser'),
('Paul Oakenfold'),
('Psognar'),
('RL Grime'),
('Rustie'),
('Sasha'),
('SBTRKT'),
('Shadow Child'),
('ShockOne'),
('Skrillex'),
('Solomun'),
('Sunnery James'),
('Ryan Marciano'),
('The Chainsmokers'),
('The Prophet'),
('Tommie Sunshine'),
('Totally Enormous Extinct Dinosaurs'),
('Yves V'),
('Andrew Bayer'),
('Yousef'),
('Swanky Tunes'),
('Shermanology'),
('Leroy Styles'),
('Fatboy Slim'),
('Bambi'),
('Bassjackers'),
('Michael Calfan'),
('Otto Knows'),
('Felguk'),
('Flapjack'),
('Flapjackers'),
('Audien'),
('La Fuente'),
('Shogun'),
('Destructo'),
('Afrojack'),
('Style of Eye'),
('Ferry Corsten'),
('Orjan Nilsen'),
('Manufactured Superstars'),
('Sultan'),
('Ned Shepard'),
('Hard Rock Sofa'),
('Jack Beats'),
('Super8'),
('Tab'),
('Wildstylez'),
('Brenan Heart'),
('MIghty Fools'),
('Baauer'),
('EDX'),
('ATB'),
('Lane 8'),
('Mat Zo'),
('Bobby Burns'),
('Paul Oakenfold'),
('Baauer'),
('RL Grime'),
('Conspirator'),
('Orjan Nilsen'),
('Skream'),
('The M Machine'),
('Kill the Noise'),
('John O\'Calaghan'),
('Fehrplay'),
('Kyau'),
('Albert'),
('Alvaro'),
('Datsik'),
('Gesaffelstein'),
('Sasha'),
('Myon'),
('Shane 54'),
('Korsakoff'),
('Riva Star'),
('Psyko Punkz'),
('Dirty Dutch'),
('HIIO'),
('Zatox'),
('Mitchell Niemeyer'),
('Wasted Penguinz'),
('Code Black'),
('ASYS'),
('Nutzbeatz'),
('Infected Mushroom'),
('Moby'),
('James Blake'),
('Night Owl Experience'),
('Mariano Trocca'),
('Olivier Weiter'),
('Adrian De Bernardi'),
('Festa Bros'),
('Geck-O'),
('Prefix'),
('Density'),
('Digital Punk'),
('Adam Beyer'),
('Degos'),
('Re-Done'),
('Chain Reaction'),
('Luna'),
('Frequencerz'),
('Crazibiza'),
('DJ Shadow'),
('Gent'),
('Jawns'),
('TJR'),
('B-Front'),
('Victor Niglio'),
('Artic'),
('Dillytek'),
('Hard Driver'),
('Jordan Suckley'),
('Jorn van Deynhoven'),
('Adrian Lux'),
('Robert Delong'),
('Stafford Brothers'),
('Dj Falcon'),
('Kenny Dope'),
('Roger Sanchez'),
('Guy J'),
('Guti'),
('Marco V'),
('Mike Vale'),
('Robert Dietz'),
('Cosmic Gate'),
('Dusky'),
('Seven Lions'),
('Orjan Nilsen'),
('Flux Pavilion vs Doctor P'),
('Nunos Dos Santos'),
('Ryan Davis'),
('Oliver Huntemann'),
('Timo Maas'),
('Joel Mull'),
('Mr. Jones'),
('Len Faki'),
('Some Chemistry'),
('Joseph Capriati'),
('Alan Fitzpatrick'),
('Fairmont'),
('Sub Focus'),
('Modestep'),
('Playboyz'),
('Anja Schneider'),
('Pan-Pot'),
('Rodriguez Jr.'),
('Funkerman'),
('Dosem'),
('Marco Bailey'),
('Tomy DeClerque'),
('Barem'),
('Dirtyphonics'),
('Hernan Cattaneo'),
('Sven Vath'),
('Stefan Dabruck'),
('Seth Troxler'),
('Raver''s Nature'),
('Mirko Loko'),
('Danny Avila'),
('Miss Kitten'),
('Nick Curly'),
('Westbam'),
('Chris Liebing'),
('Darius Syrossian'),
('AN21'),
('Ida Engberg'),
('Agoria'),
('Benny Rodrigues'),
('Darin Epsilon'),
('Christian Smith'),
('Dave Clark'),
('Firebeatz'),
('Zomboy'),
('Max Vangeli'),
('SikDuo'),
('Gabriel Arnanda'),
('Guy Gerber'),
('Estroe'),
('Jesse Voorn'),
('Jay Lumen'),
('Tom Staar'),
('Prok'),
('Fitch');
